# Generated by Django 6.0 on 2025-12-13 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module',
            old_name='is_locked_by_default',
            new_name='is_locked',
        ),
    ]
