# Generated by Django 6.0 on 2025-12-13 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_rename_is_locked_by_default_module_is_locked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='is_locked',
        ),
    ]
